kmp: KMP_algorithm.cpp
	g++ -o kmp KMP_algorithm.cpp

permutation: my_permutation.cpp
	g++ -o permutation my_permutation.cpp

all: KMP_algorithm.cpp my_permutation.cpp
	g++ -o kmp KMP_algorithm.cpp && g++ -o permutation my_permutation.cpp

clean:
	rm kmp permutation
