test: utils.h test.h sort.h utils.cpp test.cpp main.cpp insert_sort.cpp shell_sort.cpp bubble_sort.cpp quick_sort.cpp select_sort.cpp
	g++ -o test utils.cpp test.cpp main.cpp insert_sort.cpp shell_sort.cpp bubble_sort.cpp quick_sort.cpp select_sort.cpp

clean:
	rm test
